name = "FluxGoodies"
uuid = "dcc44ff8-9cc2-11e9-192c-9d0d02188c41"
authors = ["Jan Drchal"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
